[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
build_flags =
    -Isrc
    -Isrc/board
    -Isrc/bsp/LCD
    -Isrc/bsp/uart
    -Iinclude
build_src_filter =
    +<*>
    -<module/>
upload_protocol = serial
upload_port = COM4
upload_speed = 115200
upload_flags =
    -g
    0x08000000
monitor_port = COM4
monitor_speed = 115200
monitor_filters =
    time
    default
monitor_dtr = 0
monitor_rts = 0
